## Ejemplos de transmisión

Si a.shape es (5,1), b.shape es (1,6), c.shape es (6,) y d.shape es () de modo que d es un escalar,

+ Entonces a, b, c, y d son todos ampliables a la dimensión (5,6); y

+ a actúa como un arreglo (5,6) donde un [:, 0] se transmite a las otras columnas,

+ b actúa como un arreglo (5,6) donde b [0 ,:] se transmite a las otras filas,

+ c actúa como un arreglo (1,6) y, por lo tanto, como un arreglo (5,6) donde c [:] se transmite a cada fila, y finalmente,

+ d actúa como un arreglo (5,6) donde se repite el valor único.

In [2]:
import numpy as np
# a es un arreglo de ceros de la forma (5,1)
a = np.zeros([5, 1])
a, a.shape

(array([[0.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 (5, 1))

In [15]:
# a sigue teniendo la forma (5,1) y se han asignado valores aleatorios
a = np.random.randn(*a.shape)
a

array([[-0.28567953],
       [-0.46383043],
       [ 0.74527098],
       [ 0.6349167 ],
       [-1.32080638]])

In [16]:
# a.shape es (5,1)
a.shape

(5, 1)

In [17]:
# b.shape es (1,6)
b = np.ones([1,6])
b

array([[1., 1., 1., 1., 1., 1.]])

In [18]:
# c.shape es (6,)
c = np.empty([6,])
c

array([1., 1., 1., 1., 1., 1.])

In [21]:
# d.shape es (); d es un escalar
d = np.empty([])
d, d.shape

(array(5.1e-322), ())

In [24]:
# suma de a + b
a_mas_b =a + b
print(a_mas_b.shape, a_mas_b)

(5, 6) [[ 0.71432047  0.71432047  0.71432047  0.71432047  0.71432047  0.71432047]
 [ 0.53616957  0.53616957  0.53616957  0.53616957  0.53616957  0.53616957]
 [ 1.74527098  1.74527098  1.74527098  1.74527098  1.74527098  1.74527098]
 [ 1.6349167   1.6349167   1.6349167   1.6349167   1.6349167   1.6349167 ]
 [-0.32080638 -0.32080638 -0.32080638 -0.32080638 -0.32080638 -0.32080638]]


In [25]:
# multiplicar a * d
a_por_d = a * d
print(a_por_d.shape, a_por_d)

(5, 1) [[-1.43e-322]
 [-2.37e-322]
 [ 3.80e-322]
 [ 3.21e-322]
 [-6.72e-322]]


In [26]:
# multiplicar a * c
a_por_c = a * c
print(a_por_c.shape, a_por_c)

(5, 6) [[-0.28567953 -0.28567953 -0.28567953 -0.28567953 -0.28567953 -0.28567953]
 [-0.46383043 -0.46383043 -0.46383043 -0.46383043 -0.46383043 -0.46383043]
 [ 0.74527098  0.74527098  0.74527098  0.74527098  0.74527098  0.74527098]
 [ 0.6349167   0.6349167   0.6349167   0.6349167   0.6349167   0.6349167 ]
 [-1.32080638 -1.32080638 -1.32080638 -1.32080638 -1.32080638 -1.32080638]]


## Usando funciones universales

Ver https://numpy.org/doc/stable/reference/ufuncs.html

In [28]:
mark = {False: ' -', True: ' Y'}
def print_table(ntypes):
    print('X ' + ' '.join(ntypes))
    print()
    for row in ntypes:
        print(row, end='')
        for col in ntypes:
            print(mark[np.can_cast(row, col)], end='')
        print()

print_table(np.typecodes['All'])

X ? b h i l q p B H I L Q P e f d g F D G S U V O M m

? Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y - Y
b - Y Y Y Y Y Y - - - - - - Y Y Y Y Y Y Y Y Y Y Y - Y
h - - Y Y Y Y Y - - - - - - - Y Y Y Y Y Y Y Y Y Y - Y
i - - - Y Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
l - - - Y Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
q - - - - - Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
p - - - - - Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
B - - Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y - Y
H - - - Y Y Y Y - Y Y Y Y Y - Y Y Y Y Y Y Y Y Y Y - Y
I - - - - - Y Y - - Y Y Y Y - - Y Y - Y Y Y Y Y Y - Y
L - - - - - Y Y - - Y Y Y Y - - Y Y - Y Y Y Y Y Y - Y
Q - - - - - - - - - - - Y Y - - Y Y - Y Y Y Y Y Y - -
P - - - - - - - - - - - Y Y - - Y Y - Y Y Y Y Y Y - -
e - - - - - - - - - - - - - Y Y Y Y Y Y Y Y Y Y Y - -
f - - - - - - - - - - - - - - Y Y Y Y Y Y Y Y Y Y - -
d - - - - - - - - - - - - - - - Y Y - Y Y Y Y Y Y - -
g - - - - - - - - - - - - - - - Y Y - Y Y Y Y Y Y - -
F - - - - - - - - - - - - -

In [29]:
np.typecodes?

In [30]:
np.can_cast?

## Asignar contenido de una lista, Serie o array a una nueva columna

mylist = [...]

Solo se asigna directamente:

df['new_col'] = mylist

#### Convertida a Serie
se = pd.Series(mylist)
df['new_col'] = se.values

#### Convertida a array
df['new_col'] = np.array(mylist)



## Adicionar una columna con insert()

df.insert(loc=0, column='new_column', value=column_values)